# Generated by Django 3.0.6 on 2020-06-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaryApp', '0003_auto_20200623_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
