# Generated by Django 3.0.6 on 2020-06-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaryApp', '0004_auto_20200623_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
